// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsssQZqHCJ4ZPCivDFMRxBUBsNM1wggpk',
    appId: '1:602785777707:web:3b75864cd2d2d85a63426e',
    messagingSenderId: '602785777707',
    projectId: 'library-47048',
    authDomain: 'library-47048.firebaseapp.com',
    storageBucket: 'library-47048.appspot.com',
    measurementId: 'G-LG0NYJ0G0B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkuYf-V0GxsgSpFkFb8_pQNiM_ow8xHIs',
    appId: '1:602785777707:android:7cb8a63eb075a70863426e',
    messagingSenderId: '602785777707',
    projectId: 'library-47048',
    storageBucket: 'library-47048.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBl9AnLz6sihe1nQv0i1v1DL1fO6GLhaQ',
    appId: '1:602785777707:ios:fb71418c20bfd57663426e',
    messagingSenderId: '602785777707',
    projectId: 'library-47048',
    storageBucket: 'library-47048.appspot.com',
    iosClientId: '602785777707-qt2aehh69lec7d94p01gucebq29qs6ib.apps.googleusercontent.com',
    iosBundleId: 'com.example.libraryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBl9AnLz6sihe1nQv0i1v1DL1fO6GLhaQ',
    appId: '1:602785777707:ios:fb71418c20bfd57663426e',
    messagingSenderId: '602785777707',
    projectId: 'library-47048',
    storageBucket: 'library-47048.appspot.com',
    iosClientId: '602785777707-qt2aehh69lec7d94p01gucebq29qs6ib.apps.googleusercontent.com',
    iosBundleId: 'com.example.libraryApp',
  );
}
